### ISSUE TITLE
No support for tagged VLAN nodediscover?

### ISSUE THREAD

**Issue by Obihoernchen** [xcat2/confluent#107]
Hi,

is there really no support to do node discovery with tagged VLAN for IMM/XCC?
Or do I just miss something?

I can't find anything in the documentation / code and confluent does not seem to use xCATs `bmcvlantag` attribute at all.

**Comment by jjohnson42** [comment]
Currently, confluent doesn't do any in-band bmc configuration, as such shared and vlan currently has to be taken care ahead of time.

The issue is that for fully out of band discovery to work, it has to at least be on the network in some way to begin with.  For 'dedicated' and SD530 chassis, by default they are on a network even if the IP is wrong, but that can be overcome.

In a few months, we hope to have OS deploy and by extension either deploying bmc config during a dedicated 'genesis' boot or alternatively during an install or boot.

**Comment by Obihoernchen** [comment]
Hi @jjohnson42 thank you for your fast answer!
Going to use plain xCAT for recovery then, though I really liked the auto offline discovery ;)

**Comment by jjohnson42** [comment]
For reference, there is a confluent2xcat that can be used to use the confluent pxe discovery and push the mac to xCAT.   About the only thing this does nicer is letting the user skip the dynamic range.

For reference, it's not complete yet but the confluent os deploy no longer requires a boot into genesis to start discovery, discovery in testing occurs so quickly that the node's 'real' identity is known soon enough to answer the DHCPDISCOVER with the 'final' identity before the node has done anything.  That discovery can work either with no dhcpd running, or with a dhcpd running without any control over DHCP by confluent.
